book/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
]
urlpatterns += static(settings.MEDIA_URL,
                      document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root = settings.STATIC_ROOT)

books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('book_list/', views.book_list_view),
    path('book_list/<int:id>/', views.book_detail_view),
    path('books/new/', views.book_create),
    path('books/<int:pk>/edit/',views.book_update),
    path('books/<int:pk>/delete/', views.book_delete),
]

books/models.py
from django.db import models
class Book(models.Model):
    GENRE_CHOICES = [
        ('fiction', 'Fiction'),
        ('nonfiction', 'Non-fiction'),
        ('fantasy', 'Fantasy'),
        ('science_fiction', 'Science Fiction'),
        ('mystery', 'Mystery'),
        ('biography', 'Biography'),
    ]
    LIKE_OR_DISLIKE = (
        ('👍🏻', '👍🏻'),
        ('👎🏻', '👎🏻'),

    )

    title = models.CharField(max_length=255, verbose_name='Название книги', null=True)
    author = models.CharField(max_length=255, verbose_name='Автор', null=True)
    genre = models.CharField(max_length=50,choices=GENRE_CHOICES, verbose_name='Жанр', null=True)
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    cover_image = models.ImageField(upload_to='books/', verbose_name='Обложка книги', null=True, blank=True)
    like_or_dislike = models.CharField(max_length=100, choices=LIKE_OR_DISLIKE, verbose_name='Нравится или нет',
                                       null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания', null=True)

# Create your models here.
    def __str__(self):
        return f'{self.title} - {self.created_at}'

class ReviewPost(models.Model):
    post_review = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='review_post')
    text_post = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.text_post} - {self.created_at}'

class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Cloth(models.Model):
    name = models.CharField(max_length=100)
    tags = models.ManyToManyField(Tag, related_name='clothes')

    def __str__(self):
        return self.name

books/forms.py
from django import forms
from . import models


class BookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = "__all__"

books/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . import models
from .models import Book
from .forms import BookForm


# Для отображения полной информации о книге
def book_detail_view(request, id):
    if request.method == 'GET':
        post_id = get_object_or_404(models.Post, id=id)
        return render(
            request,
            template_name='book_detail.html',
            context={
                'post_id': post_id
            }
        )




# вывод не полной информации
def book_list_view(request):
    if request.method == "GET":
        # query запрос
        post_object = models.Post.objects.all()
        return render(
            request,
            template_name='book_list.html',
            context={
                'post_object': post_object
            }
        )



from .models import Cloth, Tag

def filter_products(request):
    tag_name = request.GET.get('tag')
    if tag_name:
        tag = Tag.objects.filter(name=tag_name).first()
        products = Cloth.objects.filter(tags=tag)
    else:
        products = Cloth.objects.all()

    tags = Tag.objects.all()
    return render(request, 'filter_products.html', {'products': products, 'tags': tags})






# Чтение всех книг (Read)
def book_list(request):
    books = Book.objects.all()
    return render(request, 'book_list.html', {'books': books})

# Просмотр одной книги
def book_detail(request, pk):
    book = get_object_or_404(Book, pk=pk)
    return render(request, 'book_detail.html', {'book': book})

# Создание новой книги (Create)
def book_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('book_list')
    else:
        form = BookForm()
    return render(request, 'book_form.html', {'form': form})

# Обновление книги (Update)
def book_update(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect('book_detail', pk=book.pk)
    else:
        form = BookForm(instance=book)
    return render(request, 'book_form.html', {'form': form})

# Удаление книги (Delete)
def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        book.delete()
        return redirect('book_list')
    return render(request, 'book_confirm_delete.html', {'book': book})





















#def about_me(request):
#    return HttpResponse("Информация обо мне: Ваше имя, возраст, увлечения.")

#def about_friend(request):
#    return HttpResponse("Информация о друге: Имя друга, возраст, увлечения.")

#def current_time(request):
#    now = datetime.now()
#    current_time = now.strftime("%Y-%m-%d %H:%M:%S")
#    return HttpResponse(f"Текущее время: {current_time}")

templates/book_detail.html
{% load static %}
{% include 'header.html' %}
<link rel="stylesheet" href="{% static 'css/book_list.css' %}">
h1 class="text_color">Все новости</h1>

    <h1>{{ book.title }}</h1>
    <p>Автор: {{ book.author }}</p>
    <p>Жанр: {{ book.get_genre_display }}</p>
    <p>Дата публикации: {{ book.published_date }}</p>
    <p>Количество страниц: {{ book.pages }}</p>
    <p>Издатель: {{ book.publisher }}</p>
    <p>ISBN: {{ book.isbn }}</p>
    <p>Цена: ${{ book.price }}</p>
    <p>Описание: {{ book.description }}</p>
    <a href="{% url 'book_list' %}">Назад к списку</a>

<div class="center">
    {% for j in post_id.review_post.all %}
    <p>
        <h3>{{ j.text_post }}</h3>
    </p>
    <p>{{ j.created_at }}</p>
    {% endfor %}
</div>

{% include 'footer.html' %}

templates/book_list.html
{% load static %}
{% include 'header.html' %}
<link rel="stylesheet" href="{% static 'css/book_list.css' %}">
h1 class="text_color">Все новости</h1>


<h1>Список книг</h1>

{% for book in books %}
    <div class="square_mom">
{% for i in post_object %}
<h1>Список книг</h1>
    <a href="{% url 'book_create' %}">Добавить книгу</a>
    <ul>
        {% for book in books %}
            <li>
                <a href="{% url 'book_detail' book.pk %}">{{ book.title }}</a>
                <a href="{% url 'book_update' book.pk %}">Изменить</a>
                <a href="{% url 'book_delete' book.pk %}">Удалить</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endfor %}

{% include 'footer.html' %}

templates/crub/book_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Удалить книгу</title>
</head>
<body>
    <h1>Вы уверены, что хотите удалить "{{ book.title }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
    </form>
    <a href="{% url 'book_list' %}">Назад к списку</a>
</body>
</html>

templates/crub/book_form.html
{% load static %}
{% include 'header.html' %}
<link rel="stylesheet" href="{% static 'css/create_form.css' %}">
<body>
    <h1>{{ form.instance.pk|default:"Добавить книгу" }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
    <a href="{% url 'book_list' %}">Назад к списку</a>
{% include 'footer.html' %}

templates/filter_product.html
{% include 'header.html' %}
<br><br><br>



<h1>Фильтрация продуктов</h1>

    <form method="get" action="">
        <label for="tag">Выберите категорию:</label>
        <select name="tag" id="tag">
            <option value="">Все</option>
            {% for tag in tags %}
                <option value="{{ tag.name }}">{{ tag.name }}</option>
            {% endfor %}
        </select>
        <button type="submit">Фильтровать</button>
    </form>

    <ul>
        {% for product in products %}
            <li>{{ product.name }} - {{ product.description }} ({{ product.price }}$)</li>
        {% empty %}
            <li>Нет доступных продуктов</li>
        {% endfor %}
    </ul>

{% include 'footer.html' %}

templates/footer.html
</body>
</html>
<!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

templates/header.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Навбар</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Ссылка</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Выпадающий список
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Действие</a></li>
            <li><a class="dropdown-item" href="#">Другое действие</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Что-то еще здесь</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Отключенная</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск">
        <button class="btn btn-outline-success" type="submit">Поиск</button>
      </form>
    </div>
  </div>
</nav>